site_name: Mi pagina principal
site_author: Asier Perez
site_url: https://asierperez31.github.io

theme:
  name: material
  search:
    enabled: false

nav:
  - Inicio: index.md
  - Proyectos: proyectos.md
  - Contacto: contacto.md

markdown_extensions:
  - attr_list