site_name: Mi pagina principal
site_author: Asier Perez
site_url: https://asierperez31.github.io

theme:
  name: material

nav:
  - Inicio: index.md
  - Proyectos: proyectos.md
  - Contacto: contacto.md

plugins:
  - search: false

markdown_extensions:
  - attr_list