site_name: Mi pagina principal
site_author: Asier Perez
site_url: https://asierperez31.github.io

nav:
  - Inicio: index.md
  - Sobre mi: sobre-mi.md
  - Proyectos: proyectos.md
  - Contacto: contacto.md

repo_url: https://github.com/AsierPerez31/AsierPerez31.github.io